
Neos:
  EventSourcing:
    EventStore:
      stores:
        'default':
          boundedContexts:
            '*': true
          storage: 'Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage'
          storageOptions:
            eventTableName: neos_eventsourcing_eventstore_events
#            backendOptions:
#              driver: pdo_mysql
#              host: 127.0.0.1
#              dbname: null
#              user: null
#              password: null
#              charset: utf8
  Flow:
    persistence:
      doctrine:
        migrations:
          ignoredTables:
            neos_eventsourcing_eventstore_events: true
